NationalCentreTruthReconciliation/Secure-Record-Transfer

- bagitobjecttransfer/recordtransfer/templates/recordtransfer/profile.html
> Use changed url name

- bagitobjecttransfer/recordtransfer/jobs.py
Resolves #13 
Again, if you want to ignore this that is fine too.
> Remove port from domains for email addresses

- bagitobjecttransfer/recordtransfer/bagger.py
- bagitobjecttransfer/recordtransfer/jobs.py
- bagitobjecttransfer/recordtransfer/utils.py
- bagitobjecttransfer/recordtransfer/views.py
Resolves #25 
Only thing I wasn't sure about was naming the internal variable `logger`. Maybe that is too close to `LOGGER`? If so, let me know and I can change to `internal_logger` or `custom_logger` or something.
`./docker/logs/django-rq/rqworker.log` now looks like
```
INFO 2021-06-04 13:48:08,701 worker: default: recordtransfer.jobs.bag_user_metadata_and_files({'agreement_accepted': True, 'contact_name': 'Bob', 'job_title': 'asd', 'ph..., <SimpleLazyObject: <User: admin>>) (d6cab6f0-e647-43d0-93b0-0cbab13f76b3)
INFO 2021-06-04 13:48:08,709 jobs: Creating a bag from the transfer submitted by admin
INFO 2021-06-04 13:48:08,712 jobs: Creating serializable CAAIS metadata from form data
INFO 2021-06-04 13:48:08,714 jobs: Flattening CAAIS metadata to be used as BagIt tags
INFO 2021-06-04 …
```
> Pass logger to some methods

- bagitobjecttransfer/bagitobjecttransfer/settings/base.py
- bagitobjecttransfer/bagitobjecttransfer/settings/docker.py
- bagitobjecttransfer/bagitobjecttransfer/settings/sphinx.py
- bagitobjecttransfer/recordtransfer/forms/__init__.py
- bagitobjecttransfer/recordtransfer/forms/transfer_forms.py
- bagitobjecttransfer/requirements.txt
Add django-recaptcha package, add captcha field to sign up form and transfer submit form.
> Issue 55 captcha

- bagitobjecttransfer/Dockerfile
- bagitobjecttransfer/requirements.txt
Also remove those unneeded requirements
> Centos is dead, use RockyLinux instead

- bagitobjecttransfer/recordtransfer/apps.py
- bagitobjecttransfer/recordtransfer/settings.py
> Verify recordtransfer.settings on ready()

- bagitobjecttransfer/recordtransfer/forms/transfer_forms.py
- bagitobjecttransfer/recordtransfer/settings.py
- bagitobjecttransfer/recordtransfer/views.py
- docs/code/settings.rst
Add configuration setting to change Date widgets to text fields
I was also asked to make the Province/State field have a similar prompt to the country field, as well as adding some character limitations.
Those changes can be filtered out of this PR if they are an issue.
Resolves #74
> Add character limits to some fields

- bagitobjecttransfer/recordtransfer/caais.py
- bagitobjecttransfer/recordtransfer/forms/transfer_forms.py
> Add Contact Assessment field to step 4

- bagitobjecttransfer/docker-compose.yml
- bagitobjecttransfer/docker/clamav/clamd.conf
- bagitobjecttransfer/docker/clamav/freshclam.conf
- bagitobjecttransfer/recordtransfer/jobs.py
- bagitobjecttransfer/recordtransfer/settings.py
- bagitobjecttransfer/recordtransfer/static/recordtransfer/js/forms.js
- bagitobjecttransfer/recordtransfer/templates/recordtransfer/systemerror.html
- bagitobjecttransfer/recordtransfer/urls.py
- bagitobjecttransfer/recordtransfer/views.py
- bagitobjecttransfer/requirements.txt
- docs/code/settings.rst
Resolves: #60
The message says that an administrator would be notified, but I did not add sending an email here. As the file is not accepted into the bag, do you still want that to happen and if so what would you like it to say.
For testing this I used the EICAR test file, as in [this example](https://rtcamp.com/tutorials/mail/server/testing/antivirus/)
> Add clamav and scanning

- bagitobjecttransfer/recordtransfer/jobs.py
- bagitobjecttransfer/recordtransfer/templates/recordtransfer/email/_base_email.html
> Add link back to site profile page

- bagitobjecttransfer/recordtransfer/views.py
This adds on to the Save Transfer ability to also save data from the current form.
> Save current form data when saving transfer

- bagitobjecttransfer/recordtransfer/forms/transfer_forms.py
- bagitobjecttransfer/recordtransfer/static/recordtransfer/css/transferform.css
- bagitobjecttransfer/recordtransfer/templates/recordtransfer/transferform_formset.html
- bagitobjecttransfer/recordtransfer/templates/recordtransfer/transferform_group.html
- bagitobjecttransfer/recordtransfer/templates/recordtransfer/transferform_standard.html
> Make required fields have a visual difference

- bagitobjecttransfer/bagitobjecttransfer/settings/base.py
- bagitobjecttransfer/bagitobjecttransfer/urls.py
- bagitobjecttransfer/recordtransfer/settings.py
- bagitobjecttransfer/requirements.txt
- docs/code/settings.rst
Add `DBTEMPLATES_ENABLED` setting, and disable auto-populating templates.
> Address Issue 136 (dbtemplates auto-loads templates on first startup)

- bagitobjecttransfer/bagitobjecttransfer/settings/base.py
- bagitobjecttransfer/clamav/__init__.py
- bagitobjecttransfer/clamav/apps.py
- bagitobjecttransfer/clamav/connection.py
- bagitobjecttransfer/clamav/management/commands/wait_for_clamav.py
- bagitobjecttransfer/clamav/scan.py
- bagitobjecttransfer/clamav/settings.py
- bagitobjecttransfer/example.dev.env
- bagitobjecttransfer/example.prod.env
- bagitobjecttransfer/recordtransfer/apps.py
- bagitobjecttransfer/recordtransfer/settings.py
- bagitobjecttransfer/recordtransfer/views.py
- docs/settings/index.rst
Split ClamAV code to new app, and validate there.
> Address CLAMAV_HOST and CLAMAV_PORT are not validated

- bagitobjecttransfer/compose.prod.yml
- bagitobjecttransfer/docker/nginx/nginx.conf
Add networks: and add healthcheck: to compose.prod.yml.
> Address Explicitly state networks: in compose.prod.yml 

- bagitobjecttransfer/bagitobjecttransfer/settings/docker_dev.py
- bagitobjecttransfer/bagitobjecttransfer/settings/docker_prod.py
- docs/settings/index.rst
Add REDIS_HOST, REDIS_PORT, and REDIS_PASSWORD. Also, add them to settings.rst
> Address Add redis config options to settings

- bagitobjecttransfer/recordtransfer/caais.py
- bagitobjecttransfer/recordtransfer/static/recordtransfer/css/transferform.css
- bagitobjecttransfer/recordtransfer/tests/test_caais.py
Fix bug with other fields not being added to form metadata, and fix failing tests.
> Address "Other" fields are not being picked up

- bagitobjecttransfer/bagitobjecttransfer/settings/docker_prod.py
- bagitobjecttransfer/bagitobjecttransfer/settings/production.py
Regarding [issue 184](https://github.com/NationalCentreTruthReconciliation/Secure-Record-Transfer/issues/184).
Is this everything needed for this issue?
> add log handlers for clamav

- Containerfile
- bagitobjecttransfer/bagitobjecttransfer/settings/docker_prod.py
Regarding https://github.com/NationalCentreTruthReconciliation/Secure-Record-Transfer/issues/190
> Move containerfile to root

- bagitobjecttransfer/recordtransfer/tests/test_context_processors.py
closes [issue 185](https://github.com/NationalCentreTruthReconciliation/Secure-Record-Transfer/issues/185)
> change deprecated assertEquals to assertEqual

- .githooks/pre-commit
- .gitignore
- DEVELOPERS.md
- The git configuration command to use this repo's git hooks can possibly be automated with Poetry by defining it as an entry script.
> Add pre-commit hook to add and update linting configuration

- DEVELOPERS.md
- bagitobjecttransfer/bagitobjecttransfer/settings/base.py
- bagitobjecttransfer/bagitobjecttransfer/settings/test.py
- bagitobjecttransfer/manage.py
- bagitobjecttransfer/recordtransfer/constants.py
- bagitobjecttransfer/recordtransfer/emails.py
- bagitobjecttransfer/recordtransfer/forms/__init__.py
- bagitobjecttransfer/recordtransfer/forms/admin_forms.py
- bagitobjecttransfer/recordtransfer/forms/user_forms.py
- bagitobjecttransfer/recordtransfer/static/recordtransfer/css/base/base.css
- bagitobjecttransfer/recordtransfer/static/recordtransfer/js/profile/profile.js
- bagitobjecttransfer/recordtransfer/templates/includes/dropzone_js.html
- bagitobjecttransfer/recordtransfer/templates/includes/messages.html
- bagitobjecttransfer/recordtransfer/templates/includes/profile_js.html
- bagitobjecttransfer/recordtransfer/templates/recordtransfer/email/account_updated.html
- bagitobjecttransfer/recordtransfer/templates/recordtransfer/messages.html
- bagitobjecttransfer/recordtransfer/templates/recordtransfer/profile.html
- bagitobjecttransfer/recordtransfer/tests/test_forms.py
- bagitobjecttransfer/recordtransfer/tests/test_views.py
- bagitobjecttransfer/recordtransfer/views.py
- docker/entrypoint.sh
- pyproject.toml
Closes https://github.com/NationalCentreTruthReconciliation/Secure-Record-Transfer/issues/198
Note:
- Current behaviour after resetting password is to keep the user logged in by replacing their session, as opposed to the default behaviour of logging them out of all sessions. Is this the desired behaviour?
> Ability for user to reset their password

- bagitobjecttransfer/recordtransfer/templates/recordtransfer/transferform_dropzone.html
Change `MAX_TOTAL_UPOAD_SIZE` to `MAX_TOTAL_UPLOAD_SIZE`.
> Fix variable name typo

- DEVELOPERS.md
- docs/running/index.rst
I updated the required launch.json to debug the app, and moved it to DEVELOPERS.md. There is now also a link from the Debugging setup part of the docs to the DEVELOPERS.md file.
> Address Broken Debugging Configuration

- DEVELOPERS.md
- bagitobjecttransfer/recordtransfer/tests/test_views.py
- bagitobjecttransfer/recordtransfer/urls.py
Enables disabled tests. I've also added documentation for running the tests outside of VSCode,
> Enable file upload tests regardless of settings

- DEVELOPERS.md
Adds context about how the docs and how to build them to DEVELOPERS.md.
> Add Information on Building the Documentation

- bagitobjecttransfer/recordtransfer/constants.py
- bagitobjecttransfer/recordtransfer/enums.py
- bagitobjecttransfer/recordtransfer/models.py
- bagitobjecttransfer/recordtransfer/static/recordtransfer/css/base/base.css
- bagitobjecttransfer/recordtransfer/static/recordtransfer/js/transferform/forms.js
- bagitobjecttransfer/recordtransfer/templates/recordtransfer/transferform_formset.html
- bagitobjecttransfer/recordtransfer/urls.py
- bagitobjecttransfer/recordtransfer/views.py
Closes https://github.com/NationalCentreTruthReconciliation/Secure-Record-Transfer/issues/241
> Fix initial population of FormSets from an InProgressSubmission

- Containerfile
- bagitobjecttransfer/recordtransfer/templates/admin/base_site.html
- bagitobjecttransfer/recordtransfer/templates/includes/messages.html
- bagitobjecttransfer/recordtransfer/templates/recordtransfer/footer.html
- bagitobjecttransfer/recordtransfer/templates/recordtransfer/header.html
- bagitobjecttransfer/recordtransfer/templates/recordtransfer/home.html
- bagitobjecttransfer/recordtransfer/templates/recordtransfer/signupform.html
- bagitobjecttransfer/recordtransfer/templates/recordtransfer/transferform_dropzone.html
- bagitobjecttransfer/recordtransfer/templates/recordtransfer/transferform_formset.html
- bagitobjecttransfer/recordtransfer/templates/recordtransfer/transferform_group.html
- bagitobjecttransfer/recordtransfer/templates/recordtransfer/transferform_standard.html
- docker/entrypoint.sh
- package.json
- scripts/compress_images.js
An alternative method to compressing images, that does not rely on webpack.
> Compress images using sharp

- DEVELOPERS.md
Closes https://github.com/NationalCentreTruthReconciliation/Secure-Record-Transfer/issues/268
- Included instructions on setting up virtual environment and installing poetry before installing relevant dependencies with defined extras
> Update DEVELOPERS.md documentation to use poetry

- .github/workflows/django-tests.yml
- DEVELOPERS.md
Closes https://github.com/NationalCentreTruthReconciliation/Secure-Record-Transfer/issues/266
> Github Actions workflow to require tests to pass before allowing merge

- bagitobjecttransfer/recordtransfer/static/recordtransfer/css/base/navbar.css
- bagitobjecttransfer/recordtransfer/templates/admin/base_site.html
- bagitobjecttransfer/recordtransfer/templates/recordtransfer/header.html
- Fixes the dead space under the header in the main application
- Fixes the header colours when in dark mode in the admin
> Fix Header Styling

- bagitobjecttransfer/recordtransfer/static/recordtransfer/css/profile/profile.css
- bagitobjecttransfer/recordtransfer/templates/includes/submission_group_table.html
- bagitobjecttransfer/recordtransfer/templates/includes/submission_table.html
- bagitobjecttransfer/recordtransfer/templates/recordtransfer/base.html
- bagitobjecttransfer/recordtransfer/templates/recordtransfer/profile.html
- webpack.config.js
Closes https://github.com/NationalCentreTruthReconciliation/Secure-Record-Transfer/issues/294
> Hide UUID columns on Profile page on small screen sizes

- Containerfile
- docker/entrypoint.sh
Closes https://github.com/NationalCentreTruthReconciliation/Secure-Record-Transfer/issues/297
> Run asset build in Containerfile instead of entrypoint

- bagitobjecttransfer/recordtransfer/templates/recordtransfer/transferform_sourceinfo.html
> Use webp static url instead of png for Help Icon

- bagitobjecttransfer/recordtransfer/views.py
Closes https://github.com/NationalCentreTruthReconciliation/Secure-Record-Transfer/issues/320
> Fix IndexError when saving transfer form on Review Step

- bagitobjecttransfer/recordtransfer/templates/admin/base_site.html
Closes https://github.com/NationalCentreTruthReconciliation/Secure-Record-Transfer/issues/314
I changed the header link colour to white.
> Improve contrast between header link and primary background

- bagitobjecttransfer/recordtransfer/static/recordtransfer/css/base/navbar.css
- bagitobjecttransfer/recordtransfer/static/recordtransfer/js/base/navbar.js
- bagitobjecttransfer/recordtransfer/templates/recordtransfer/header.html
I didn't want to spend too much time on CSS for making a fancy animation for the burger menu button -> close button, so I've opted for a simple icon change instead. I think the positioning of the navbar container has been improved though.
> Improve navbar burger menu close button

- bagitobjecttransfer/recordtransfer/templates/includes/submission_table.html
- bagitobjecttransfer/recordtransfer/templates/recordtransfer/profile.html
Closes https://github.com/NationalCentreTruthReconciliation/Secure-Record-Transfer/issues/333
> Fix submissions not showing for a given group in Group Details page

- bagitobjecttransfer/recordtransfer/static/recordtransfer/js/transferform/uppyForm.js
- bagitobjecttransfer/recordtransfer/static/recordtransfer/js/transferform/utils.js
- bagitobjecttransfer/recordtransfer/tests/e2e/test_e2e.py
- bagitobjecttransfer/recordtransfer/tests/unit/test_views.py
- bagitobjecttransfer/recordtransfer/urls.py
- bagitobjecttransfer/recordtransfer/views.py
- docker/nginx/templates/nginx.conf.template
Closes https://github.com/NationalCentreTruthReconciliation/Secure-Record-Transfer/issues/32
> Make File Transfer REST-ful

- bagitobjecttransfer/recordtransfer/models.py
- bagitobjecttransfer/recordtransfer/tests/unit/test_forms.py
- bagitobjecttransfer/recordtransfer/tests/unit/test_models.py
- bagitobjecttransfer/recordtransfer/tests/unit/test_views.py
- bagitobjecttransfer/recordtransfer/views.py
Closes https://github.com/NationalCentreTruthReconciliation/Secure-Record-Transfer/issues/239
> Write Tests for SubmissionGroupForm, SubmissionGroupCreateView and SubmissionGroupDetailView

- bagitobjecttransfer/recordtransfer/templates/recordtransfer/transferform_base.html
Closes https://github.com/NationalCentreTruthReconciliation/Secure-Record-Transfer/issues/350
- Include missing "messages" template in base transfer form template
> Fix Error Message Not Showing When Returning to Review Step

- conftest.py
Closes https://github.com/NationalCentreTruthReconciliation/Secure-Record-Transfer/issues/351
> Run npm install Before Asset Build in conftest.py

- bagitobjecttransfer/recordtransfer/views/transfer.py
Closes https://github.com/NationalCentreTruthReconciliation/Secure-Record-Transfer/issues/366
> Delete InProgressSubmission After Submission Is Made

- .githooks/pre-commit
- .github/workflows/sync-ruff-config.yml
- .gitignore
- DEVELOPERS.md
- ruff.toml
Closes https://github.com/NationalCentreTruthReconciliation/Secure-Record-Transfer/issues/367
> Sync ruff.toml Using Github Action

- app/recordtransfer/forms/transfer_forms.py
- app/recordtransfer/static/recordtransfer/js/transferform/submissionGroup.js
- app/recordtransfer/templates/recordtransfer/transferform_group.html
- app/recordtransfer/tests/e2e/test_e2e.py
- app/recordtransfer/views/transfer.py
- conftest.py
Closes https://github.com/NationalCentreTruthReconciliation/Secure-Record-Transfer/issues/384, https://github.com/NationalCentreTruthReconciliation/Secure-Record-Transfer/issues/386 and https://github.com/NationalCentreTruthReconciliation/Secure-Record-Transfer/issues/388
> Refactor TransferFormWizard

- app/recordtransfer/models.py
- app/recordtransfer/tests/unit/test_models.py
- app/recordtransfer/tests/unit/test_signals.py
Closes https://github.com/NationalCentreTruthReconciliation/Secure-Record-Transfer/issues/408
> Update last interaction time on file delete and in-progress submission save

- app/recordtransfer/views/transfer.py
Closes https://github.com/NationalCentreTruthReconciliation/Secure-Record-Transfer/issues/413
> Change Message Time to Local Time

- app/recordtransfer/decorators.py
- app/recordtransfer/tests/unit/test_decorators.py
- app/recordtransfer/tests/unit/views/test_media.py
- app/recordtransfer/views/media.py
- docs/code/decorators.rst
- docs/code/index.rst
Closes https://github.com/NationalCentreTruthReconciliation/Secure-Record-Transfer/issues/396
> Add Protection for File Upload Related Endpoints

- app/recordtransfer/tests/e2e/test_e2e.py
Closes https://github.com/NationalCentreTruthReconciliation/Secure-Record-Transfer/issues/407
> Fix Failing E2E Test for Review Step

- eslint.config.mjs
Closes https://github.com/NationalCentreTruthReconciliation/Secure-Record-Transfer/issues/427
> Add docs to ESLint Exclusions

- app/caais/static/caais/js/admin/phoneNumberMask.js
- app/recordtransfer/static/recordtransfer/js/profile/profile.js
- app/recordtransfer/static/recordtransfer/js/submission_group/submission_group_form.js
- app/recordtransfer/static/recordtransfer/js/transferform/index.js
- app/recordtransfer/static/recordtransfer/js/transferform/sourceInfo.js
- app/recordtransfer/static/recordtransfer/js/transferform/unsavedChanges.js
- eslint.config.mjs
- webpack.config.js
Closes https://github.com/NationalCentreTruthReconciliation/Secure-Record-Transfer/issues/426
> Fix Outstanding ESLint Issues

- package-lock.json
- package.json
- pyproject.toml
Update version strings for end-of-month February milestone completion.
> Update Version to 2025.02.28

- .github/workflows/pr-lint-check.yml
Closes https://github.com/NationalCentreTruthReconciliation/Secure-Record-Transfer/issues/428
> Create GH Action to Run Linting on Pull Request

- app/recordtransfer/admin.py
Closes https://github.com/NationalCentreTruthReconciliation/Secure-Record-Transfer/issues/419
> Make Jobs searchable in admin

- app/recordtransfer/jobs.py
> Don't zip files in memory

- app/recordtransfer/static/recordtransfer/js/transferform/widgets.js
Closes https://github.com/NationalCentreTruthReconciliation/Secure-Record-Transfer/issues/352
> Enable date range when USE_DATE_WIDGETS=False

- compose.dev.yml
- compose.prod.yml
- docker/entrypoint.sh
> Fix collectstatic being run twice

- app/caais/models.py
- app/caais/test/unit/test_models.py
- app/recordtransfer/tests/unit/views/test_profile.py
> Refactor date parsing into Metadata model

- app/app/settings/base.py
- app/app/settings/docker_prod.py
> Add hash to static files in production to allow cache busting

- docs/code/views.rst
- docs/introduction/index.rst
Updates the different operations users and admins can do with this application.
Also fixes a build error related to merging in #476 
Closes #468
> Update section "What Does this App Do?"

- app/recordtransfer/static/recordtransfer/css/base/submission_form.css
Closes https://github.com/NationalCentreTruthReconciliation/Secure-Record-Transfer/issues/487
Before:
After:
> Add more space between top of Submission Form and Navigation Bar

- app/recordtransfer/static/recordtransfer/css/base/base.css
- app/recordtransfer/static/recordtransfer/css/profile/profile.css
> Hide UUID Column on Submission Group Detail Page

- DEVELOPERS.md
Closes https://github.com/NationalCentreTruthReconciliation/Secure-Record-Transfer/issues/499
> Add information on supported OSes in DEVELOPERS.md

- DEVELOPERS.md
Closes #508 
Clean up Poetry installation docs
> Update poetry installation info

- .github/workflows/check-migrations.yml
Closes https://github.com/NationalCentreTruthReconciliation/Secure-Record-Transfer/issues/507
> Make workflow to check for unmigrated model changes

- docs/settings/index.rst
Closes https://github.com/NationalCentreTruthReconciliation/Secure-Record-Transfer/issues/517
> Fix misleading docs regarding USE_DATE_WIDGETS setting

- .vscode/extensions.json
- DEVELOPERS.md
Closes https://github.com/NationalCentreTruthReconciliation/Secure-Record-Transfer/issues/515
> Add Required Tools Section to DEVELOPERS.md

- app/recordtransfer/static/recordtransfer/css/base/footer.css
- app/recordtransfer/templates/recordtransfer/base.html
- app/recordtransfer/templates/recordtransfer/footer.html
Closes https://github.com/NationalCentreTruthReconciliation/Secure-Record-Transfer/issues/509
> Footer UI Revamp

- package.json
- pyproject.toml
Update version to coincide with end-of-month milestone.
> Update version to 2025.04.30

- app/app/settings/base.py
- app/recordtransfer/constants.py
- app/recordtransfer/static/recordtransfer/css/base/base.css
- app/recordtransfer/static/recordtransfer/css/profile/profile.css
- app/recordtransfer/templates/includes/in_progress_submission_table.html
- app/recordtransfer/templates/includes/pagination.html
- app/recordtransfer/templates/includes/submission_group_table.html
- app/recordtransfer/templates/includes/submission_table.html
- app/recordtransfer/templates/recordtransfer/base.html
- app/recordtransfer/templates/recordtransfer/profile.html
- app/recordtransfer/tests/unit/views/test_profile.py
- app/recordtransfer/urls.py
- app/recordtransfer/views/profile.py
- package-lock.json
- poetry.lock
- pyproject.toml
> Dynamically Render Table Pagination Using HTMX

- .github/workflows/django-tests.yml
- .github/workflows/e2e-tests.yml
- app/app/settings/base.py
- app/app/settings/test.py
- app/recordtransfer/tests/e2e/test_e2e.py
- docs/settings/index.rst
Closes https://github.com/NationalCentreTruthReconciliation/Secure-Record-Transfer/issues/532
> Re-instate E2E tests on Pull Request

- app/recordtransfer/models.py
- app/recordtransfer/tests/unit/test_models.py
- app/recordtransfer/tests/unit/test_utils.py
- app/recordtransfer/utils.py
Remov option logger arguments and keep the module's logger
> 540 Remove optional logger arguments

- .github/workflows/lint-js.yml
- .github/workflows/lint-py.yml
- .gitignore
- app/recordtransfer/views/__init__.py
- app/recordtransfer/views/account.py
- app/recordtransfer/views/home.py
- app/recordtransfer/views/media.py
- app/recordtransfer/views/post_submission.py
- app/recordtransfer/views/pre_submission.py
- app/recordtransfer/views/profile.py
- pyproject.toml
- uv.lock
Closes https://github.com/NationalCentreTruthReconciliation/Secure-Record-Transfer/issues/543
Change notes:
- Fixed all Ruff linting errors in `app/recordtransfer/views`
- Created a GitHub action to lint check Python code in `app/recordtransfer/views` using Ruff
> Run Ruff Linting on Pull Request

- app/recordtransfer/static/recordtransfer/css/base/base.css
- app/recordtransfer/static/recordtransfer/css/profile/profile.css
- app/recordtransfer/templates/includes/base_table.html
- app/recordtransfer/templates/includes/in_progress_submission_table.html
- app/recordtransfer/templates/includes/pagination.html
- app/recordtransfer/templates/includes/profile_form.html
- app/recordtransfer/templates/includes/submission_group_table.html
- app/recordtransfer/templates/includes/submission_table.html
- app/recordtransfer/templates/recordtransfer/base.html
- app/recordtransfer/templates/recordtransfer/profile.html
- app/recordtransfer/tests/unit/views/test_profile.py
Closes https://github.com/NationalCentreTruthReconciliation/Secure-Record-Transfer/issues/536
DaisyUI offers the ability to easily customise a theme through CSS: https://daisyui.com/docs/themes/#how-to-add-a-new-custom-theme. For e.g., setting `--color-primary` and `--color-primary-content` allows us to use these colors to style components through CSS classes such as `btn-primary` and `text-primary-content`.
DaisyUI provides a variety of convenient components, although lack more complex components such as sortable/filterable data tables or text editors. Their documentation is adaquate and easy to understand. Since DaisyUI is simply a plugin built upon Tailwind CSS, we get access to Tailwind classes as well to manage things like layout, typography, and responsiveness. Tailwind itself is …
> Restyle Profile Page using DaisyUI

- app/recordtransfer/templates/recordtransfer/submission_form_base.html
- djlint.toml
I added H029 rule to djlint.toml
Tested by formatting submission_form_base.html
> Add rule H029 to djlint.toml to ignore it

- Containerfile
- app/recordtransfer/static/recordtransfer/css/base/base.css
- app/recordtransfer/static/recordtransfer/css/profile/profile.css
- app/recordtransfer/templates/recordtransfer/profile.html
- package-lock.json
- package.json
- postcss.config.mjs
- webpack.config.js
Closes https://github.com/NationalCentreTruthReconciliation/Secure-Record-Transfer/issues/571
> Install DaisyUI as a Project Dependency

- pyproject.toml
- uv.lock
Addresses security vulnerability with setuptools.
> Upgrade setuptools

- .github/workflows/smoke-test-prod.yml
- app/recordtransfer/views/home.py
Add a workflow that starts the app up in the production configuration via Docker and checks that the homepage is returning a 200 OK response.
> Add smoke test workflow

- package-lock.json
- package.json
- pyproject.toml
- uv.lock
Final commit for [May Milestone](https://github.com/NationalCentreTruthReconciliation/Secure-Record-Transfer/milestone/6)
> Bump version to 2025.05.30

- .github/workflows/lint-py.yml
- app/recordtransfer/forms/__init__.py
- app/recordtransfer/forms/admin_forms.py
- app/recordtransfer/forms/submission_forms.py
- app/recordtransfer/forms/user_forms.py
Closes https://github.com/NationalCentreTruthReconciliation/Secure-Record-Transfer/issues/645
Notes:
- Temporarily included the feature branch [644-expand-ruff-linting](https://github.com/NationalCentreTruthReconciliation/Secure-Record-Transfer/tree/644-expand-ruff-linting) in Ruff lint check action. This change (https://github.com/NationalCentreTruthReconciliation/Secure-Record-Transfer/pull/652/commits/4b501828aa5354918ce30e599f56f9424eb9c90e) will be reverted when making a pull request to merge to `master`
- Fixed all Ruff linting errors in that module
> Add "./app/recordtransfer/forms" to ruff linting action

- app/recordtransfer/templates/recordtransfer/submission_sent.html
- app/recordtransfer/templates/registration/logged_out.html
I used hericons here to make the pages more visually attractive. Also added buttons instead of links and used primary colour as the base color for the whole page
Closes https://github.com/NationalCentreTruthReconciliation/Secure-Record-Transfer/issues/650
> 650 re style submission sent page 2

- app/recordtransfer/templates/recordtransfer/activation_invalid.html
Closes https://github.com/NationalCentreTruthReconciliation/Secure-Record-Transfer/issues/703
> 703 restyle account activation invalid

- app/recordtransfer/templates/recordtransfer/activation_sent.html
Closes https://github.com/NationalCentreTruthReconciliation/Secure-Record-Transfer/issues/702
> Restyle account activation sent page using daisy ui

- app/recordtransfer/templates/registration/password_reset_done.html
Closes https://github.com/NationalCentreTruthReconciliation/Secure-Record-Transfer/issues/694
> 694 re style password reset done page

- app/recordtransfer/templates/registration/password_reset_complete.html
Closes https://github.com/NationalCentreTruthReconciliation/Secure-Record-Transfer/issues/713
> Restyle password reset success page

- app/recordtransfer/management/commands/verify_settings.py
> Verify TEMP_STORAGE_FOLDER on startup

- app/recordtransfer/static/recordtransfer/css/main.css
- app/recordtransfer/static/recordtransfer/js/index.js
- app/recordtransfer/static/recordtransfer/js/registration/form-validation.js
- app/recordtransfer/templates/registration/password_reset_confirm.html
- app/recordtransfer/templates/registration/password_reset_confirm_errors.html
Closes https://github.com/NationalCentreTruthReconciliation/Secure-Record-Transfer/issues/712
> 712 restyle invalid link page for password change

- app/recordtransfer/static/recordtransfer/js/index.js
- app/recordtransfer/static/recordtransfer/js/registration/form-validation.js
- app/recordtransfer/templates/registration/password_reset_form.html
Closes https://github.com/NationalCentreTruthReconciliation/Secure-Record-Transfer/issues/720
All the changes requested have been made. If anything looks off let me know, I ll make the tweaks accordingly.
> 720 fix inconsistent styling on accountpassword reset

- app/recordtransfer/templates/recordtransfer/home.html
Closes https://github.com/NationalCentreTruthReconciliation/Secure-Record-Transfer/issues/718 .
I have put Merriweather as the font for headings to match the main heading, let me know what @danloveg yo think about those
> 718 fix heading styling on main page

- app/recordtransfer/forms/submission_forms.py
- app/recordtransfer/tests/e2e/test_submission_form_e2e.py
Closes https://github.com/NationalCentreTruthReconciliation/Secure-Record-Transfer/issues/619
> 619 remove condition of files field from record description form

- app/recordtransfer/views/pre_submission.py
Closes https://github.com/NationalCentreTruthReconciliation/Secure-Record-Transfer/issues/621
> 621 make other identifiers form more user friendly

- app/recordtransfer/templates/includes/frequently_asked_questions.html
- app/recordtransfer/templates/recordtransfer/help.html
- app/recordtransfer/templates/recordtransfer/submission_form_groupsubmission.html
- app/recordtransfer/views/home.py
- app/recordtransfer/views/pre_submission.py
Closes https://github.com/NationalCentreTruthReconciliation/Secure-Record-Transfer/issues/622
> 622-Address submission group feedback

- app/recordtransfer/models.py
- app/recordtransfer/tests/unit/test_models.py
Closes https://github.com/NationalCentreTruthReconciliation/Secure-Record-Transfer/issues/735
> Fix Inefficient Caching When SiteSetting Value Is None

- app/recordtransfer/views/pre_submission.py
> Fix save button not showing after review step reached

- app/recordtransfer/admin.py
> Display message when exporting groups with no submissions in admin

- app/recordtransfer/static/recordtransfer/css/base/home.css
- app/recordtransfer/templates/recordtransfer/home.html
Closes https://github.com/NationalCentreTruthReconciliation/Secure-Record-Transfer/issues/845
> 845 only text clickable in hero button

- package-lock.json
- package.json
- pyproject.toml
- uv.lock
Ran the version update script to change version.
Version coincides with [July 2025 Milestone](https://github.com/NationalCentreTruthReconciliation/Secure-Record-Transfer/milestone/8).
```shell
python scripts/update_version.py '2025.07.30'
```
> Update version 2025.7.7 -> 2025.7.30

- app/locale/hi/LC_MESSAGES/django.po
- app/recordtransfer/forms/mixins.py
- app/recordtransfer/forms/submission_forms.py
Closes https://github.com/NationalCentreTruthReconciliation/Secure-Record-Transfer/issues/829
> 829 verify strings in code can be translated

- app/locale/hi/LC_MESSAGES/django.po
- app/recordtransfer/admin.py
Closes https://github.com/NationalCentreTruthReconciliation/Secure-Record-Transfer/issues/825?issue=NationalCentreTruthReconciliation%7CSecure-Record-Transfer%7C830
> 830 verify strings in the admin site are translated

- app/recordtransfer/templates/recordtransfer/signup_form.html
Closes https://github.com/NationalCentreTruthReconciliation/Secure-Record-Transfer/issues/846
> Fix fields getting cleared after invalid form fields

- TRANSLATORS.md
Closes https://github.com/NationalCentreTruthReconciliation/Secure-Record-Transfer/issues/832
> Add docs for Translators on how translations work

- Containerfile
- webpack.config.js
Closes https://github.com/NationalCentreTruthReconciliation/Secure-Record-Transfer/issues/882
> 882 add default for webpack mode arg in containerfile

- app/recordtransfer/admin.py
- app/recordtransfer/forms/admin_forms.py
- app/recordtransfer/tests/unit/test_admin_forms.py
Closes https://github.com/NationalCentreTruthReconciliation/Secure-Record-Transfer/issues/916
> 916 issue non staff users can have staff email updates enabled

- app/caais/admin.py
> Update list display columns, add Status filter

- .github/workflows/check-compilemessages.yml
- .github/workflows/check-migrations.yml
- .github/workflows/django-tests.yml
- .github/workflows/e2e-tests.yml
- DEVELOPERS.md
- app/recordtransfer/admin.py
Closes #873 
Upgrade `uv` from 0.7.2 to 0.8.8.
> Upgrade to latest uv

- app/recordtransfer/templates/recordtransfer/submission_detail.html
> Fix Issue: Dates of creation or revision numbers inaccurate in submission report

- Containerfile
Closes https://github.com/NationalCentreTruthReconciliation/Secure-Record-Transfer/issues/983
> Change as to AS to fix FromAsCasing issue

- app/recordtransfer/templates/includes/in_progress_submission_table.html
- app/recordtransfer/templates/includes/submission_group_table.html
- app/recordtransfer/templates/includes/submission_table.html
Closes https://github.com/NationalCentreTruthReconciliation/Secure-Record-Transfer/issues/996
> Fix Tooltips hidding behind headers

- app/recordtransfer/tests/unit/views/test_post_submission.py
- app/recordtransfer/views/post_submission.py
Closes https://github.com/NationalCentreTruthReconciliation/Secure-Record-Transfer/issues/1013
> Add error when user tries to download CSV for empty group

- app/caais/admin.py
- app/caais/constants.py
- app/caais/forms.py
- app/caais/managers.py
- app/caais/test/unit/test_forms.py
- app/caais/test/unit/test_managers.py
- app/recordtransfer/forms/submission_forms.py
- app/recordtransfer/tests/unit/test_forms.py
- docs/code/caais/constants.rst
- docs/code/caais/index.rst
Closes #1018 
Disallows Accession Identifier and Accession Number to be submitted in the form.
> Fix reserved identifier names allowed

- app/recordtransfer/models.py
> Skip password history logging during fixture loading

- .github/workflows/update-messages.yml
Closes #1031 
Similar to the sync-ruff-config bot, this is a new bot that will make a pull request for updated message files, if there are any message files to update.
> Add action to make pull requests for message files

- package.json
- pyproject.toml
- uv.lock
Closes #1026
Updates version to current date.
> Update version to 2025.8.29

- package.json
- pyproject.toml
- uv.lock
Closes #1056 
Update version for new release.
> Update version -> 2025.9.29
