bagitobjecttransfer/recordtransfer/static/recordtransfer/js/forms.js, bagitobjecttransfer/recordtransfer/urls.py, bagitobjecttransfer/recordtransfer/views.py
Closes #7 
The file upload logic has changed to provide more robust uploads that don't fail if one or more files are invalid. There is a new endpoint at `/transfer/checkfiles/` that can be used to check if a file is allowed to be uploaded. In the file drop zone, this endpoint is used to check the name of the file _before_ the user even has a chance to upload it. If the name of the file is invalid, the user will not be able to submit the form, and will need to remove the file from the form before submitting.
Before, the file extension check was completed after the entire file was streamed to the server, which wasted resources.
There is also now a redundant file extension check if the user manages to circumvent the first check.
=> Transfer form invalid files

bagitobjecttransfer/docker-compose.dev.yml, docs/running/docker.rst
Hey @danloveg 
Here is the `.dockerenv` I needed to get the docker-compose setup running. I passed your code along to some other devs I work with and one hit on some of the same problems I hit. I then felt guilty as I just sent them to your docs and forgot to warn them.
I also altered the `docker-compose.dev.yml` to avoid the files as directories problems.
I did get the local development setup working, but I had to run both the django server (`python3 manage.py runserver`) and the django-rq worker (`python3 manage.py rq_worker default`) outside of docker. Inside I had problems with the rq_worker losing its connection and dying (taking the whole container down with it).
This probably should not be needed but I found this way I could connect PyCharm to the one I wanted to trace and see what …
=> Update docker-compose docs

bagitobjecttransfer/recordtransfer/static/recordtransfer/js/widgetconfig.js
Resolves #19 
It appears that when you [type in a full date](https://github.com/jquery/jquery-ui/blob/32850869d308d5e7c9bf3e3b4d483ea886d373ce/ui/widgets/datepicker.js#L725-L728) the [`_updateDatepicker`](https://github.com/jquery/jquery-ui/blob/32850869d308d5e7c9bf3e3b4d483ea886d373ce/ui/widgets/datepicker.js#L826) function is called, which calls the [`_generateHTML`](https://github.com/jquery/jquery-ui/blob/32850869d308d5e7c9bf3e3b4d483ea886d373ce/ui/widgets/datepicker.js#L1657) function to re-generate the date picker.
The `_generateHTML` just returns a string of the HTML so I override the function, call the original one, create the estimated date checkbox HTML and return both string.
As the `_generateHTML` function is called for all the other events I could remove them. 
But as it is …
=> Override generateHTML function

bagitobjecttransfer/recordtransfer/admin.py
Closes #17 
Adds a check to `save_model` to disallow any superuser from editing a superuser account.
=> Disallow non-superusers from editing superuser account

bagitobjecttransfer/bagitobjecttransfer/settings/base.py, bagitobjecttransfer/recordtransfer/admin.py, bagitobjecttransfer/recordtransfer/jobs.py, bagitobjecttransfer/recordtransfer/templates/recordtransfer/email/account_updated.html
Resolves #31 
Not sure if there is a better way to intercept the password change, my theory based on the [method in Admin](https://github.com/django/django/blob/main/django/contrib/auth/admin.py#L129-L190) is if it raised an exception that would skip the message stuff and immediately raise up to the top. Otherwise we return the form or redirect response once we have (or have not) sent the email.
=> Send emails for certain account changes

.gitattributes
Closes #48. Ensures `*.sh` files are pushed and pulled with LF line terminators.
=> Add .gitattributes to set *.sh files to LF

bagitobjecttransfer/recordtransfer/templates/recordtransfer/about.html, bagitobjecttransfer/recordtransfer/views.py
This pull request does not include any information about "security" on the about page. I do not know if this should be included, but the maximum transfer size should obviously be included. If it is deemed necessary to have security info in the about page in the future, I will add it in.
=> Add "Maximum Transfer Size" to About page

bagitobjecttransfer/requirements.txt
setuptools was complaining about the version name `3.0.1-nctr`, so I've changed the tag name to `3.0.1` and that seems to have fixed the issue.
=> Fix InvalidVersion error

bagitobjecttransfer/recordtransfer/templates/recordtransfer/transferform_base.html, bagitobjecttransfer/recordtransfer/views.py
Instead of hiding the button when you exceed the allowed number of transfers. This now hides the button if you set the `MAX_SAVED_TRANSFER_COUNT` to `0` (i.e. disable saved transfers) and shows a disabled button if you have exceeded the max count.
=> Hide or disable the Save Form button

bagitobjecttransfer/recordtransfer/forms/transfer_forms.py
Cleaning up after #98 and realized that these two fields are required by validation but not marked as such (so not getting the red asterisk). 
I couldn't figure out a way to handle the "Other" text fields which are also required (short of making custom templates), but I think the current validation is sufficient.
=> Source type and source role are required fields

bagitobjecttransfer/.dockerignore, bagitobjecttransfer/docker-compose.dev.yml, bagitobjecttransfer/manage.py, bagitobjecttransfer/requirements.txt
Resolves #124 by starting up `debugpy` when the app is run in the development container environment. Two separate instances of `debugpy` are started, one for the Django app, and one for the async jobs run via Django RQ.
=> Addresses Issue 124 (Add Debugging Config)

.readthedocs.yml
Fixed by reverting to Python 3.8. Python 3.11 is not available in readthedocs.org yet.
Documentation is verified to be working here:
https://secure-record-transfer.readthedocs.io/en/issue-128/index.html
The link above may be broken in the future.
Closes #128
=> Address Issue 128 (Read the Docs builds are Failing)

bagitobjecttransfer/bagitobjecttransfer/settings/production.py, bagitobjecttransfer/example.dev.env, bagitobjecttransfer/example.prod.env
Change default SITE_ID to "1" globally. The only remaining configuration that had a site ID of 2 was the `production.py` configuration.
=> Address Issue 109 (Site ID issue)

bagitobjecttransfer/Containerfile, bagitobjecttransfer/compose.dev.yml, bagitobjecttransfer/compose.prod.yml
Change python to 3.10 in Containerfile. Add changes to compose files so that they can be built in Docker, if needed.
=> Address Python version in compose file should be locked to major version

bagitobjecttransfer/bagitobjecttransfer/settings/base.py
Closes [issue 183](https://github.com/NationalCentreTruthReconciliation/Secure-Record-Transfer/issues/183)
I'm not sure how TIMEZONE, and other environment variables such as SECRET_KEY will be set since I could not find them in the `example.*.env` files. Perhaps these will be added later?
=> Make timezone configurable

bagitobjecttransfer/recordtransfer/templates/includes/submission_detail_css.html, bagitobjecttransfer/recordtransfer/templates/recordtransfer/base.html, bagitobjecttransfer/recordtransfer/templates/recordtransfer/submission_detail.html
Closes https://github.com/NationalCentreTruthReconciliation/Secure-Record-Transfer/issues/201
I've opted to create a similar template to `base_css.html`, called `submission_detail_css.html`, which I load into `submission_detail.html`.
I think this would be better than to include that stylesheet in `base_css.html`, since only one template will be using `recordtransfer_submission_detail_styles`.
=> Fix missing stylesheet for submission detail page

bagitobjecttransfer/bagitobjecttransfer/settings/docker_dev.py, compose.dev.yml, docs/howtouse/addingusers.rst, docs/running/index.rst
Substitutes the MailHog container for [Mailpit](https://github.com/axllent/mailpit). Relevant documentation has also been updated - there are no mentions of the word MailHog any more.
The easiest way to test that emails are being intercept by Mailpit is to submit a Sign Up form.
=> Switch from MailHog to Mailpit

bagitobjecttransfer/recordtransfer/views.py
Sends the user to `recordtransfer:transfersent` instead of `recordtransfer:userprofile`.
=> Change re-directed page to transfersent

Containerfile
This change is needed when the image is built with Podman on WSL.
=> Make Entrypoint Script Executable

DEVELOPERS.md, README.md, package.json, webpack.config.js
Adds an `npm run watch` command which can be ran in the development container to re-build assets when they change.
=> Set up webpack --watch

docker/entrypoint.sh
Closes https://github.com/NationalCentreTruthReconciliation/Secure-Record-Transfer/issues/267
- Includes the additional change to ignore image assets of .png,.jpg,.jpeg and .webp formats within `recordtransfer` during call to `collectstatic`
=> Run collectstatic in production

.readthedocs.yaml
Uses poetry instead of pip to install dependencies, since `package-mode = false` in `pyproject.toml` can't be handled with pip.
The working build can be seen here:
https://secure-record-transfer.readthedocs.io/en/273-fix-read-the-docs-build-failing/
=> Fix Read the Docs Build Failing

README.md, docs/running/index.rst
Closes https://github.com/NationalCentreTruthReconciliation/Secure-Record-Transfer/issues/272
=> Remove redundant migrate instruction in README

bagitobjecttransfer/recordtransfer/constants.py, bagitobjecttransfer/recordtransfer/forms/user_forms.py, bagitobjecttransfer/recordtransfer/static/recordtransfer/js/base/messages.js, bagitobjecttransfer/recordtransfer/static/recordtransfer/js/profile/profile.js, bagitobjecttransfer/recordtransfer/static/recordtransfer/js/transferform/forms.js, bagitobjecttransfer/recordtransfer/templates/includes/profile_form.html, bagitobjecttransfer/recordtransfer/templates/recordtransfer/profile.html, bagitobjecttransfer/recordtransfer/tests/test_forms.py, bagitobjecttransfer/recordtransfer/tests/test_views.py, bagitobjecttransfer/recordtransfer/views.py
Closes https://github.com/NationalCentreTruthReconciliation/Secure-Record-Transfer/issues/251
Additional changes:
- Added a `reset` method to `UserProfileForm` to reset the form to original values after an invalid form submission
- Added tests for first and last name form fields
- Removed unnecessary form data for test cases, such as `get_email_notification` field when testing password changes or password fields when testing email notification changes.
- Fixed issue of messages not being dismissed after close button is clicked
=> Allow user to update their first and last name

bagitobjecttransfer/recordtransfer/forms/transfer_forms.py, bagitobjecttransfer/recordtransfer/static/recordtransfer/js/transferform/dropzoneForm.js, bagitobjecttransfer/recordtransfer/templates/django_recaptcha/includes/js_v2_invisible.html, bagitobjecttransfer/recordtransfer/templates/recordtransfer/base.html, bagitobjecttransfer/recordtransfer/templates/recordtransfer/transferform_base.html
Closes https://github.com/NationalCentreTruthReconciliation/Secure-Record-Transfer/issues/237
It turns out that the `captcha/js_v2_invisible.html` template was not actually being used to properly override `django_recaptcha/includes/js_v2_invisible.html`. The original template was still being used despite this in `base.html`:
```html
{% if FILE_UPLOAD_ENABLED %}
{% include "captcha/js_v2_invisible.html" %}
{% endif %}
```
I've renamed that file (`captcha/js_v2_invisible.html`) to match the same folder structure as the actual `include` used in the source code so that Django renders our custom template instead.
It looks like there was difficulty in overriding this exact same template in a past issue https://github.com/NationalCentreTruthReconciliation/Secure-Record-Transfer/issues/92.
=> Fix invisible reCAPTCHA breaking Previous Step button on final step

DEVELOPERS.md, eslint.config.mjs, package-lock.json, package.json, webpack.config.js
Closes https://github.com/NationalCentreTruthReconciliation/Secure-Record-Transfer/issues/282
Notes:
- In addition to the [recommended rules](https://eslint.org/docs/latest/rules) (rules with a green tick beside them) defined by ESLint, I have also included some additional rules which can be found in the bottom section of `eslint.config.mjs`.
- ESLint deprecated all their formatting rules last year, but they recommend using the [ESLint Stylistic Plugin](https://eslint.style/), which I'm using
- I'm also using `eslint-plugin-import` in place of the [`sort-imports` rule](https://eslint.org/docs/latest/rules/sort-imports) since it's not able to fix all import sorting problems that it highlights
- Another plugin that's used is `eslint-plugin-jsdoc` for enforcing docstrings for JS functions
- …
=> Add ESLint configuration

bagitobjecttransfer/recordtransfer/static/recordtransfer/css/base/base.css, bagitobjecttransfer/recordtransfer/static/recordtransfer/css/base/modal.css, bagitobjecttransfer/recordtransfer/static/recordtransfer/js/transferform/modal.js, bagitobjecttransfer/recordtransfer/static/recordtransfer/js/transferform/unsavedChanges.js, bagitobjecttransfer/recordtransfer/templates/includes/unsaved_transferform_modal.html, bagitobjecttransfer/recordtransfer/templates/recordtransfer/banner.html, bagitobjecttransfer/recordtransfer/templates/recordtransfer/base.html, bagitobjecttransfer/recordtransfer/templates/recordtransfer/footer.html, bagitobjecttransfer/recordtransfer/templates/recordtransfer/header.html, bagitobjecttransfer/recordtransfer/templates/recordtransfer/transferform_base.html, bagitobjecttransfer/recordtransfer/templates/recordtransfer/transferform_rights.html, bagitobjecttransfer/recordtransfer/templates/recordtransfer/transferform_sourceinfo.html
Closes https://github.com/NationalCentreTruthReconciliation/Secure-Record-Transfer/issues/283
Change notes:
- Displays a custom warning modal when user clicks on any navigational link while on the transfer form (except when on the first step of a fresh form)
- Triggers browser's default dialog when user attempts to close tab or exit browser
Additional note:
- Submission of form in the final step is broken, but not from my changes. I'm looking into what's causing it - I think it might be related to this bug: https://github.com/NationalCentreTruthReconciliation/Secure-Record-Transfer/issues/237
(EDIT: this was not the cause of the issue, it was due to errors in `dropzoneForm.js`)
=> Add protection from clicking away from form

.github/workflows/publish-to-ghcr.yml, Containerfile, compose.dev.yml, compose.prod.yml
Closes https://github.com/NationalCentreTruthReconciliation/Secure-Record-Transfer/issues/310
Passes `WEBPACK_MODE` as an `arg` from the compose files to the Containerfile, and sets it as an environment variable  there, which `npm run build` has access to.
=> Fix undefined WEBPACK_MODE in Containerfile

bagitobjecttransfer/recordtransfer/models.py, bagitobjecttransfer/recordtransfer/utils.py, bagitobjecttransfer/recordtransfer/views.py
Fixes all remaining non-lazy log calls, and removes the non-standard `msg=()` syntax.
=> Fix non-lazy logging calls

conftest.py, pyproject.toml
Closes https://github.com/NationalCentreTruthReconciliation/Secure-Record-Transfer/issues/343
Uses a pytest hook to call `npm run build` before any E2E test is run:
- https://docs.pytest.org/en/stable/how-to/writing_plugins.html#making-your-plugin-installable-by-others
- https://docs.pytest.org/en/stable/how-to/writing_hook_functions.html
=> Automate Static Asset Build for E2E Tests

bagitobjecttransfer/recordtransfer/templates/recordtransfer/base.html
Closes https://github.com/NationalCentreTruthReconciliation/Secure-Record-Transfer/issues/357
- Preloads footer image in the head tag of the base template
=> Prevent Footer Image from Flickering

DEVELOPERS.md, app/app/settings/test.py, app/recordtransfer/tests/e2e/test_e2e.py, app/recordtransfer/tests/unit/test_models.py, app/recordtransfer/tests/unit/views/test_media.py, poetry.lock, pyproject.toml
Closes #349
The tests now work whether you're using `manage.py`, `pytest`, or the VS Code test explorer.
I removed a package that was only being used when run via `manage.py`. Since the tests are running fine without that package, I've decided to remove it.
=> Fix running tests when using manage.py

app/caais/static/caais/css/base/metadataChangeForm.css
Closes https://github.com/NationalCentreTruthReconciliation/Secure-Record-Transfer/issues/383
It should look like this now:
=> Fix stretched country icon when editing CAAIS metadata in admin

.github/workflows/sync-ruff-config.yml
Closes https://github.com/NationalCentreTruthReconciliation/Secure-Record-Transfer/issues/400
Perhaps renaming `ruff_new.toml` into the existing `ruff.toml` is causing this unexpected behaviour of the `ruff_new.toml` being committed. `cp` is used in place of `mv` potentially fix this issue.
=> Copy contents instead of moving file

compose.prod.yml
Closes #406 
I have verified that both the dev and prod containers are now working in both Docker and Podman. I made a few simplifications to the prod compose file to bring it in line with the dev container.
Here is the dev container running in Podman:
And here is the prod container running in Podman with the latest changes on this branch (you can see the image is tagged `secure-record-transfer-prod`):
The reason I removed `WEBPACK_MODE` from the container's `env:` is that it's only needed when the container is built in production. The reason it's included as an `env:` variable in the dev containers is so that running Webpack uses the proper configuration (whereas Webpack can't be run in the prod containers).
=> Test Compose Files in Podman & Docker

app/caais/forms.py, app/caais/static/caais/css/base/metadataChangeForm.css, app/caais/widgets.py
Closes #456 
Wraps the original rendered HTML for the `CountrySelectField` in a div, so that they are displayed side-by-side. The issue before was that the flag was a direct child of a flexbox containing the select field and the flag image, which meant that on a small screen, the flag image gets wrapped onto a separate row, causing it to fill up the available width of the entire flexbox.
=> Fix large flag in CAAIS Metadata admin change form on small screen size

docs/admin/index.rst, docs/code/caais.rst, docs/code/configuration.rst, docs/code/decorators.rst, docs/code/emails.rst, docs/code/forms.rst, docs/code/jobs.rst, docs/code/models.rst, docs/code/utils.rst, docs/code/views.rst, docs/conf.py, docs/howtouse/transferform.rst, docs/index.rst, docs/running/index.rst, docs/settings/index.rst
Closes #461 
- Change doc settings for modules so that members without an explicit docstring will not be included within the docs. This means that any class attributes that you want to document should be included as part of the class's docstring.
- Removed "_static" from `html_static_path` in `docs.conf.py`, as this directory does not exist and the docs currently do not use custom static assets.
=> Fix Sphinx documentation build warnings

app/recordtransfer/static/recordtransfer/css/base/base.css, app/recordtransfer/static/recordtransfer/css/submission_form/review_step.css, app/recordtransfer/templates/includes/submission_table.html, app/recordtransfer/templates/recordtransfer/submission_group_show_create.html
Closes #481 
In addition, clicking on the "Click to view report" on the Past Submissions table of the Profile page causes the report to open up on a new tab, rather than on the same tab.
=> Add Link to Profile on Submission Group Page

package-lock.json, package.json, pyproject.toml
Version update to coincide with the [March 2025](https://github.com/NationalCentreTruthReconciliation/Secure-Record-Transfer/milestone/4) milestone.
=> Update version to 2025.03.21

LICENSE
This pull request adds the GNU General Public License version 3 (GPLv3) to the repository. The GPLv3 license:
- Ensures the software remains free and open source
- Protects users' freedom to run, study, share, and modify the software
- Requires that derivative works also remain under the same license
- Provides patent protection for users
- Aligns with the project's open-source goals
The Secure Record Transfer application is designed to help institutions manage transfers of files and metadata following the Canadian Archival Accession Information Standard (CAAIS). By using the GPLv3 license, we ensure that this tool remains freely available to all institutions that need it.
=> Add GNU GPLv3 license

.vscode/settings.json, docs/running/index.rst
Closes https://github.com/NationalCentreTruthReconciliation/Secure-Record-Transfer/issues/547
Change notes:
- Mentioned `docker compose` can be used in place of `podman-compose` in Sphinx docs
- Removed individual Docker-equivalent commands from Sphinx docs
- Added text wrapping setting for RST files, since line breaks within a single paragraph are handled by the rendering application and explicitly including them do not make a difference
=> Standardize Podman/Docker Mentions in Sphinx Docs 

app/recordtransfer/static/recordtransfer/css/base/navbar.css, app/recordtransfer/templates/recordtransfer/header.html
I made the nav-items-container and nav-toggle-button wrap into nav-wrapper. Did so that they both can be stay fixed and scrolled together. Sticky wasn't working very well. Fixed worked because it bypasses layout issues , it’s immune to parent styling.
=> Make mobile navigation menu fixed

app/recordtransfer/tests/unit/views/test_post_submission.py, app/recordtransfer/urls.py, app/recordtransfer/views/post_submission.py
Closes https://github.com/NationalCentreTruthReconciliation/Secure-Record-Transfer/issues/580
The two instances where `get_object_or_404` were being used without filtering for the user did not actually pose any security risks, as the view utilized `test_func()` as part of `UserPassesTestMixin` to test that the object requested belonged to `request.user`. However, this is not ideal, since we want to prevent any objects that don't belong to `request.user` from making it to the view in the first place.
I've made use of user filtering directly in `get_queryset()`, so that it returns a queryset appropriate to the user or staff member.
I've also added missing tests for `SubmissionDetailView` and `SubmissionCsvView`.
=> Simplify Permission Handling for Post Submission Views

app/recordtransfer/static/recordtransfer/css/base/base.css, app/recordtransfer/static/recordtransfer/css/base/navbar.css, app/recordtransfer/static/recordtransfer/js/base/navbar.js, app/recordtransfer/templates/recordtransfer/header.html
Closes #522 
This change makes the mobile menu `position: fixed;` and ensures it stays at ~ 20px from the top of the screen. I've also made it so that the menu stays aligned with the title in the header so that the positioning of the menu icon looks good when scrolled all the way to the top.
This is a combo of my own changes and @Eashana0104's (see #587)
=> Make mobile menu stick to top when scrolled down

app/recordtransfer/static/recordtransfer/js/profile/delete_ip_submission.js, app/recordtransfer/static/recordtransfer/js/profile/forms.js, app/recordtransfer/static/recordtransfer/js/profile/htmx.js, app/recordtransfer/static/recordtransfer/js/profile/index.js, app/recordtransfer/static/recordtransfer/js/profile/utils.js, app/recordtransfer/templates/includes/base_modal.html, app/recordtransfer/templates/includes/delete_in_progress_submission_modal.html, app/recordtransfer/templates/includes/in_progress_submission_table.html, app/recordtransfer/templates/includes/new_submission_group_modal.html, app/recordtransfer/templates/recordtransfer/profile.html, app/recordtransfer/tests/unit/views/test_post_submission.py, app/recordtransfer/tests/unit/views/test_profile.py, app/recordtransfer/urls.py, app/recordtransfer/views/post_submission.py, app/recordtransfer/views/profile.py, webpack.config.js
Closes https://github.com/NationalCentreTruthReconciliation/Secure-Record-Transfer/issues/570
Change notes:
- Adds ability to create a new submission group using a modal directly from the Profile page, instead of loading a separate page
- Changes the way modals are rendered: modal's contents are being replaced now instead of the entire modal itself. This is to prevent the modal from flickering.
=> Use Modal to Create New Submission Groups on Profile Page

app/recordtransfer/static/recordtransfer/js/base/tooltip.js, app/recordtransfer/templates/recordtransfer/submission_form_rights.html, app/recordtransfer/templates/recordtransfer/submission_form_sourceinfo.html
The "Click here" links that take you to the help page were incorrectly re-directing to the about page. As well, the tooltips may invisibly cover these links because their display is not being set to `none` when they are hidden.
These changes fix both of these problems.
=> Fix issues with click here links to view help

app/recordtransfer/decorators.py, app/recordtransfer/tests/unit/test_decorators.py, app/recordtransfer/views/media.py
Closes https://github.com/NationalCentreTruthReconciliation/Secure-Record-Transfer/issues/627
This issue was caused by the `requires_upload_step` decorator requiring both file upload and file access operations to be restricted to the upload step. I've changed it so that:
1) file uploads and deletes are restricted to just the Upload Files step
2) uploaded file access is restricted to the Upload Files and Review step
=> Fix Not Being Able to Access Uploaded Files on Review Step

app/recordtransfer/static/recordtransfer/css/base/tooltip.css
Closes https://github.com/NationalCentreTruthReconciliation/Secure-Record-Transfer/issues/668
Removed `z-index` property from `help-icon` class. I believe the `z-index` that we were setting is greater than or equal to to the `z-index` of hover elements like the date-picker and tooltips, causing the help icons to be displayed in front.
=> Fix Help Icons Showing In Front of Hover Elements

.github/workflows/django-tests.yml, .github/workflows/e2e-tests.yml, .github/workflows/lint-js.yml, .github/workflows/lint-py.yml, .github/workflows/smoke-test-prod.yml, app/recordtransfer/forms/submission_forms.py
Closes https://github.com/NationalCentreTruthReconciliation/Secure-Record-Transfer/issues/639?issue=NationalCentreTruthReconciliation%7CSecure-Record-Transfer%7C615. I looked for select fields with other as an option and only could find one field where Other was at top instead of bottom, moved it to bottom.
=> Move other to bottom when selecting provinces

app/recordtransfer/templates/registration/password_reset_email.html
Closes https://github.com/NationalCentreTruthReconciliation/Secure-Record-Transfer/issues/696
I updated the styling of the password reset email to be consistent with the new email styling.
=> Update styling of password reset email

DEVELOPERS.md, package-lock.json, package.json, pyproject.toml, scripts/update_version.py, uv.lock
Adds a script that can be used to update the version without having to manually update the `package.json`, `package-lock.json`, and `pyproject.toml` files.
Additionally, updates the version to `2025.07.07` for today's release.
=> Add script to update version, update version

.github/workflows/django-tests.yml, .github/workflows/sync-ruff-config.yml
Closes #753
Sets explicit permissions for the unit test and Ruff config sync workflows
=> Add permissions to workflows for unit tests and Ruff sync

app/recordtransfer/static/recordtransfer/js/submission_form/submissionGroup.js
Closes #757
Although defined as an async function, `fetchSubmissionGroups` was not actually waiting on the fetch to resolve first (no await is used within . It was returning immediately, even before groups and group descriptions have been fetched & populated. `updateGroupDescription` was being called before `fetchSubmissionGroups` could resolve, meaning the selected option had no `data-attribute` populated.
I've fixed this so that `fetchSubmissionGroups` `await`s for a response before continuing, and updating the group description display upon form initialization.
=> Fix Group Description does not populate when returning to form

app/recordtransfer/templates/recordtransfer/submission_form_base.html, app/recordtransfer/tests/e2e/test_submission_form_e2e.py
Closes #776 
This issue is that the "Click to save form and resume later" button does not exist on the Review Step. The reason for this is that the user would not be interested in saving the form at the final Review Step.
However, the "Save form and resume later" button on the unsaved changes modal relies on the former button to perform the save. To address this, I've made it so that the "Click to save form and resume later" button is included as a hidden button in every step, and is displayed conditionally, so that it can still be used by the modal even when it's not visible.
=> Fix Saving Form from Unsaved Changes Modal Does Not Work on Review Step

package-lock.json, package.json
This change is for CVE-2025-5889. The offending package was the brace-expansion package (version 2.0.1), which has been replaced with a different package that does not have this vulnerability.
=> Address security issue by upgrading glob

app/recordtransfer/forms/mixins.py, app/recordtransfer/widgets.py
Closes #782 
Change notes:
- Duplicate the `CustomCountrySelectWidget` that already exists in `caais.widgets` within `recordtransfer.widgets`
=> Fix Stretched Country Icon in UserAdmin Change Form

Containerfile, docker/entrypoint.sh
Closes #797
A persistent cache mount is now used for `uv` which notably speeds it up.
Additionally, I was struggling with the file permissions in the production container again due to the named volume being given the permissions `root:root` by default. This change fixes that by allowing the permissions to be changed after the `app` container starts.
=> Use cache mount for uv, fix prod permissions

app/clamav/connection.py, app/clamav/scan.py, app/recordtransfer/tests/unit/views/test_media.py, app/recordtransfer/views/media.py, compose.dev.yml, compose.prod.yml, docker/clamav/Dockerfile, docker/clamav/clamd.conf.template, docker/clamav/entrypoint.sh, pyproject.toml, uv.lock
Closes https://github.com/NationalCentreTruthReconciliation/Secure-Record-Transfer/issues/813
Change notes:
- Raised relevant errors from `check_for_malware` and handled errors properly in `views.media.upload_or_list_files`
- Made ClamAV scan limits (see https://linux.die.net/man/5/clamd.conf) configurable using `envsubst`. I had to create a custom clamav image and install `gettext` (which comes with `envsubst`) in it to make this happen. This is unlike the `nginx` image, which already comes with `envsubst` installed, and variable replacement logic.
=> Replace `clamd` with `clamav-client`, make scan limits configurable

app/recordtransfer/management/commands/devrqworker.py, compose.dev.yml
Closes https://github.com/NationalCentreTruthReconciliation/Secure-Record-Transfer/issues/698
Creates a wrapper command for the [`rqworker`](https://github.com/rq/django-rq?tab=readme-ov-file#running-workers) management command that auto-restarts the worker upon code changes using [`autoreload.run_with_reloader`](https://github.com/django/django/blob/a8536e33da6365fb7bba901a06a67d163d0d4c8a/django/utils/autoreload.py#L662).
=> Auto-Restart RQ Worker on Code Changes

app/recordtransfer/templates/recordtransfer/in_progress_submission_expired.html
Closes https://github.com/NationalCentreTruthReconciliation/Secure-Record-Transfer/issues/843
Restyled it to match the submission/sent page, as the attributes were largely the same—only the content differed.
=> 843 re style in progress submission expired

app/recordtransfer/templates/recordtransfer/submission_form_review.html
Closes https://github.com/NationalCentreTruthReconciliation/Secure-Record-Transfer/issues/889
Long file names now break and wrap to the next line if they exceed the container width. They break at any character though.  Using word-break: break-all ensures that overly long names don’t overflow the layout.
I avoided using word-break: keep-all because in many browsers, file names (especially with underscores or no spaces) don’t break naturally, which could cause overflow issues again.
I also tried using overflow-wrap:break-word, it didn't work; it was still overflowing even after breaking, and it wasn't understanding the file-entry boundaries
=> 889 long file names overflow step 8 summary card on review step

app/recordtransfer/tests/unit/views/test_media.py, app/recordtransfer/views/media.py
Closes #890 
Adds the **Content-Type** and **Content-Disposition** headers to zip file responses. This makes it so NGINX does not change the file name when it's downloaded.
This change can only be tested in production mode.
=> Fix job zip file names

app/recordtransfer/templates/recordtransfer/submission_form_base.html
Closes https://github.com/NationalCentreTruthReconciliation/Secure-Record-Transfer/issues/895
This update adds transition:true to the hx-swap attribute, allowing HTMX to automatically handle transitions before and after content swaps. This results in a much smoother visual experience and eliminates the flickering that was previously occurring during swaps.
=> Fix Flickering by Enabling Transitions in HTMX Swaps

app/recordtransfer/tests/unit/test_utils.py, app/recordtransfer/utils.py
This PR fixes an issue with the `get_js_translation_version` function when there are no ~~`djangojs.po`~~ `djangojs.mo` files.
=> Fix issue with empty list passed to `max()`

DEVELOPERS.md
Closes #824
Documents the `-aE` options to make a fresh docs build. Also, adds the `uv run` prefix to these commands, since that will work even if the virtual environment isn't active.
=> Document how to make a "clean" docs build

.dockerignore, Containerfile, docker/entrypoint.sh
Closes #878 
Runs `compilemessages` when the image is run so that `.mo` files are present when the app starts.
`gettext` was missing from the production container so I've added that in.
=> Compile messages on app start

app/recordtransfer/static/recordtransfer/js/submission_form/widgets.js
Sets the locale object in air-datepicker based on the current HTML document's language.
Unfortunately, there is no `hi` locale, only `en` and `fr`. See here: https://github.com/t1m0n/air-datepicker/tree/v3/src/locale
Uses the English locale by default.
=> Set locale in air-datepicker

app/recordtransfer/forms/admin_forms.py, app/recordtransfer/models.py
Closes #884 
Unfortunately, since `PermUploadedFile` is not a foreign key of `Submission`, it's be very difficult to render an inline of these indirectly related models.
I've settled for a simpler solution: updating the `__str__` of the UploadSession to make it more human readable, and adding a help text that says to click the upload session's name to view files uploaded in that submission.
Before:
After:
It looks more friendly now, in my opinion.
=> Add info to admin for finding files

app/recordtransfer/static/recordtransfer/js/submission_form/unsavedChanges.js
Closes #933 
Excluded any links within the django debug toolbar from triggering the unsaved changes modal
=> Fix Issue: Clicking Django debug toolbar links on form opens save modal

compose.dev.yml
Closes #955 
The `app` service doesn't need a restart policy because Django's `runserver` handles all exceptions gracefully, so the container never exits. This is in contrast with the `rq` service, for which the container exits after the worker process crashes. To fix this, I've added a restart policy to the `rq` service.
=> Fix Issue: RQ worker auto-restart causes container to exit on exception

app/app/settings/base.py
Closes #945 
The context provided by this context processor is not being used in any of our templates, which is why it is being removed.
=> Remove debug context processor from all configurations

conftest.py
Closes #969 
Checks if tests are only being collected (i.e., not run) and skips building static assets with Webpack if that's the case.
=> Skip running `npm run build` when only discovering tests

app/recordtransfer/static/recordtransfer/css/base/base.css, app/recordtransfer/static/recordtransfer/css/base/home.css, app/recordtransfer/static/recordtransfer/css/base/navbar.css, app/recordtransfer/templates/recordtransfer/home.html
Closes https://github.com/NationalCentreTruthReconciliation/Secure-Record-Transfer/issues/905
Change notes-
- Moved the navbar outside of the #main-container to prevent layout overlap.
- Applied DaisyUI styling enhancements to home.html.
- Removed unused CSS from home.css as it was no longer needed due to DaisyUI.
- Added smooth transitions to improve responsiveness when switching between different screen sizes.
=> 905 home page styles break on short screens

app/caais/admin.py, app/caais/managers.py, app/caais/models.py, app/recordtransfer/admin.py, app/recordtransfer/managers.py, app/recordtransfer/models.py, app/recordtransfer/tests/unit/views/test_post_submission.py, app/recordtransfer/views/post_submission.py
Closes #1011
Adds CSV export to the Metadata admin.
You can now export a CSV from six different places:
- **From the metadata admin**
- From the user profile submission table
- From the user profile submission group table
- From the submission group detail view
- From the submission group admin
- From the submission admin
Since all the fields that are exported are in the Metadata model, I've moved the `export_csv` out of `recordtransfer` and into the `caais` app. A CSV can now be exported from both the Metadata manager, and any Metadata queryset.
=> Add CSV export to metadata admin

app/fixtures/seed_data.json, app/recordtransfer/forms/submission_forms.py, app/recordtransfer/static/recordtransfer/js/submission_form/uppyForm.js, app/recordtransfer/static/recordtransfer/js/submission_form/utils.js, app/recordtransfer/tests/unit/test_forms.py, app/recordtransfer/tests/unit/views/test_media.py, app/recordtransfer/tests/unit/views/test_pre_submission.py, app/recordtransfer/tests/unit/views/test_profile.py, app/recordtransfer/urls.py, app/recordtransfer/views/media.py, app/recordtransfer/views/pre_submission.py
Closes #1040 
Removes the upload session creation endpoint, and handles creating the upload session internally.
Uses the `extra_data` field on the session storage to store the session token, and passes that token via the JS context to the template. Instead of the uppy form loading the session token from the input field, it's now loaded via context.
When the submission form is saved, the extra data is also saved. And of course, when the submission form is loaded, this extra data is also loaded.
I've additionally added some more security measures to the UploadFilesForm, namely:
1. The UploadSession objects weren't being filtered by user in the `clean()` function, and now they are.
2. Catches errors where the user tampers with the hidden session_token input.
=> Remove upload session endpoint

app/recordtransfer/jobs.py, app/recordtransfer/models.py, app/recordtransfer/tests/e2e/test_submission_form_e2e.py, app/recordtransfer/tests/unit/test_jobs.py, app/recordtransfer/tests/unit/views/test_pre_submission.py, app/recordtransfer/views/pre_submission.py
Closes #1042 
Adds a new `django_rq.job` for copying uploads to perm storage. Two new additions were made:
1. The copy is tried one more time if it fails the first time
2. The temp storage folder is removed after moving all the files
=> Move uploads to permanent storage asynchronously
